services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    command: npm run dev
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
